// lwml test module: fft2d
// lwml, (c) ltwood

// This file is automatically generated by 'mktm.lua', no hands!

#ifndef _TEST_FFT2D_
#define _TEST_FFT2D_

#include "defs.h"
#include "mdefs.h"

/*#lake:stop*/

namespace lwml_test {

using namespace lwml;

bool test_fft2d();

}; // namespace lwml_test

#endif // _TEST_FFT2D_
