// lwml test module: rfft
// lwml, (c) ltwood

// This file is automatically generated by 'mktm.lua', no hands!

#ifndef _TEST_RFFT_
#define _TEST_RFFT_

#include "defs.h"
#include "mdefs.h"

/*#lake:stop*/

namespace lwml_test {

using namespace lwml;

bool test_rfft();

}; // namespace lwml_test

#endif // _TEST_RFFT_
